# Generated by Django 6.0.1 on 2026-02-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_court'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Facility', 'verbose_name_plural': 'Facilities'},
        ),
    ]
