# Generated by Django 6.0.1 on 2026-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facility_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='sport',
            field=models.CharField(blank=True, choices=[('football', 'Nogomet'), ('basketball', 'Košarka'), ('tennis', 'Tenis'), ('padel', 'Padel'), ('other', 'Ostalo')], max_length=20, null=True),
        ),
    ]
