# Generated by Django 6.0.1 on 2026-02-19 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_court_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='facility',
            name='working_from',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='facility',
            name='working_till',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
