# Generated by Django 6.0.1 on 2026-02-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_court_price_per_hour_facility_working_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='price_per_hour',
        ),
    ]
