# Generated by Django 6.0.1 on 2026-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Na čekanju'), ('confirmed', 'Potvrđeno'), ('cancelled', 'Otkazano')], default='pending', max_length=20),
        ),
    ]
