# Generated by Django 6.0.1 on 2026-02-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_approve_booking', 'Can approve booking')]},
        ),
    ]
